name: FreeRDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Downloading Ngrok and resources
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/30dayscoding/rdp/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/30dayscoding/rdp/main/wallpaper.jpg -OutFile wallpaper.jpg
        Invoke-WebRequest https://raw.githubusercontent.com/30dayscoding/rdp/main/wallpaper.bat -OutFile wallpaper.bat

    - name: Extract Ngrok
      run: Expand-Archive ngrok.zip -DestinationPath ngrok

    - name: Set Ngrok authtoken
      run: |
        .\ngrok\ngrok.exe config add-authtoken "$env:NGROK_AUTH_TOKEN"
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable RDP on Windows
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Copy-Item wallpaper.jpg D:\a\wallpaper.jpg
        Copy-Item wallpaper.bat D:\a\wallpaper.bat

    - name: Start Ngrok tunnel
      run: |
        Start-Process -WindowStyle Hidden -FilePath ngrok\ngrok.exe -ArgumentList "tcp 3389"
        Start-Sleep -Seconds 10
        Invoke-RestMethod -Uri http://127.0.0.1:4040/api/tunnels > ngrok_info.json
        Get-Content ngrok_info.json

    - name: Run RDP startup script
      run: cmd /c start.bat

    - name: Keep session alive
      run: |
        Invoke-WebRequest https://github.com/30dayscoding/rdp/raw/main/loop.ps1 -OutFile loop.ps1
        powershell -ExecutionPolicy Bypass -File .\loop.ps1
